# Generated by Django 2.2.3 on 2020-02-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectivechat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='url_extension',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_id',
            field=models.CharField(default='sdlf', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
